apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgA43UcZZBn7g19Ys65fDr31KhEjrvm3DgjNPVpt2KRngu8m+rDQmQYh3jYPFWvF0xTRJHTxPqSF4h5aOrT36uRtxO4jYEjel/W8mkLJeBkV3QvNW7m5QBhD203ex/Y/J/aBzf6zzxatv0YMN8z+f195yh+gSKk0HqK6ejCzjFmnSTj4EbC64xBS3ECWHBhaT3hLckpXBc/wUMQZbqv7Xy2V2Bh0IPk9Iy48owCOEw2D127bSpmBPmgis8LhMUVtiYBpVsVOzMxSGqpHu6mZNToe4oId5Vid9S8+HX9Fqkma2EdyNYxjJVNYesXNU4h8BZ+vu5QVfCop2gQzTz8zxHlnceDWN4O1CGCW/ImCkmjvNgRLUxxMP4tpAEqUI3aY6I/ue8LmOh4Hns1U+rtKE/mUQVaBw+7KA4t2oax9rsrh0z23wfFNIgKOUtJRQAhzNxD7IEVrz4VYaNCKkZIuhkoBJYwXmygc60kltXFqFV09FZQABSrze55gaS8eHoP1lOAOBBtJaERjmhoUrhgSQUvt37F2XSU/2aJP1d+mZgUoVC0pnaNDZhM29qOMeFflRHCQXzXJFGE/vUrfUUJ53+6wUnxWC75OaNSToT7O5UITtcdyDMOkpDjJTBnwgP2Kzk2/nJDPlJ+E3KF0j7vnIRz4vqjRHT7joJh2iJR0x8qcWZPFochyjjer8hP/wAMfUnQEnish5/pFvN3ptcB+QwctTsY2uOW7ATJtwaOr2+oGjd9J913X+XPS
    username: AgCikHhghQf8TZKJJlbVbKXFejH3DKZ/yz1E25IzFMne0LvixyTsjHBUwZ15zZ8E3Fc41gWHGR6LjTvU8aXfgCXotAcX7b9qbKonc41zV669ybNfac7hVPi1ynvZ4pYK3hu6lYa2ccfpN6r0gOaePx5B6uucGw+b39na0FyFhMKfT7tX8ODM3+2RasrHNo4Q7Zk2BMp2YupubyYUtA3roG2/LuK4kZWo4A58oQiM7p8dhiDQgtz35/77h3FZn54pNHL1YSEZXTCYhYbgfGCV5bw5yyo/4YaS8JF1wbEYJQJB3sKgi92ukOhbDJMXSeaJVVC/CWs6KvlppHBsN0PFCC6sVvxbaEuGq5mdNGetCm3X7KJLR9zgVvqll1pFwg7vc3v6ACJZP2Igt2/JEF+fJtIkFT+shGX+wfWSj7ObuCM9cJKdLIdbK1UcH5X2ll4Ihh11SPSosUqRQb9Ultk/TrmU2htUUWSDONn5RJJh1usnzKraL8BEHPclKej7XJIJIVH17Pa4VV/8Wp7io8pxVjADS6bGuYMSyg4GcjWseGx2bEvjKeN1qT+S1U+R3ASfCeeB8WOxT+bX5gH6of4+zY+BxLBy1gPRVGVB3B0EX4Sx2IJTqwHLicTz+mBOvrjJnaFMsDzq8gZPMRCzpl+rdXrIb1g+VLVl4rkk5krkX7IrefwIMSYKpwcR8HRIXYdPG+tt6JVbpgM/PZR1DReTr6RUqzVyV4bRHxI=
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

