apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm1
  annotations:
    argocd.argoproj.io/sync-wave: "300"
    helm.sh/hook-weight: "300"
spec:
  template:
    pod:
      containers:
      - name: qmgr
        env:
        - name: MQSNOAUT
          value: "yes"
        volumeMounts:
          - name: config-volume-scripts
            mountPath: /mq-config
            readOnly: true
            #optional: true
          - name: dynamic-config-volume-mqsc
            mountPath: /dynamic-mq-config-mqsc
            readOnly: true
            #optional: true
      volumes:
        - name: config-volume-scripts
          configMap:
            name: scripts-configmap
            defaultMode: 0777
        - name: dynamic-config-volume-mqsc
          configMap:
            name: dynamic-mqsc-configmap
            defaultMode: 0777
